### ISSUE TITLE
Question about the version of pip packages

### ISSUE THREAD

**Issue by CAIROCharlie** [OptiMaL-PSE-Lab/pulsed-reactor-optimisation#1]
Hello!

 I've noticed that many dependency packages have undergone updates, including `gpjax`. It seems you might be using a version prior to `0.5.6`, whereas the latest version of gpjax no longer features the `add_parameter` function. Could you please share the version of all pip packages you're utilizing? Thank you very much.

**Comment by trsav** [comment]
Hello, yes this is correct! I'll get these dependencies added ASAP.

**Comment by trsav** [comment]
Done in a4897a1. As a side note the repository here https://github.com/trsav/reactor_benchmark presents a more 'focussed' set of code solely for specifying and simulating reactor geometry, complete with Docker image for installing OpenFOAM and swak4FOAM library.

**Comment by CAIROCharlie** [comment]
Thank you very much for your reply. I would like to clarify if my understanding is correct that the repository at https://github.com/OptiMaL-PSE-Lab/pulsed-reactor-optimisation is not considered a black box and offers more flexibility in terms of modifications compared to the repository at https://github.com/trsav/reactor_benchmark?
